apiVersion: v1
kind: Namespace
metadata:
  name: multi-agent-a2a
  labels:
    name: multi-agent-a2a
    purpose: ai-ops-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-ops-secrets
  namespace: multi-agent-a2a
type: Opaque
data:
  openai-api-key: ""  # Base64 encoded OpenAI API key
  langsmith-api-key: ""  # Base64 encoded LangSmith API key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: multi-agent-a2a
data:
  log-level: "INFO"
  metrics-enabled: "true"
  a2a-protocol-version: "1.0.0"
  system-name: "Multi-Agent A2A AI-Ops System"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: multi-agent-a2a
  name: agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-rolebinding
  namespace: multi-agent-a2a
subjects:
- kind: ServiceAccount
  name: default
  namespace: multi-agent-a2a
roleRef:
  kind: Role
  name: agent-role
  apiGroup: rbac.authorization.k8s.io