apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-agent
  namespace: multi-agent-a2a
  labels:
    app: research-agent
    component: agent
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: research-agent
  template:
    metadata:
      labels:
        app: research-agent
        component: agent
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: research-agent
        image: a2a-research-agent:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
          name: http
        - containerPort: 8083
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: AGENT_PORT
          value: "8083"
        - name: AGENT_HOST
          value: "0.0.0.0"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: research-agent-secrets
              key: openai-api-key
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: research-agent-secrets
              key: langsmith-api-key
              optional: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /.well-known/agent-card.json
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: research-agent-service
  namespace: multi-agent-a2a
  labels:
    app: research-agent
spec:
  selector:
    app: research-agent
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: research-agent-secrets
  namespace: multi-agent-a2a
type: Opaque
data:
  openai-api-key: ""  # Base64 encoded OpenAI API key
  langsmith-api-key: ""  # Base64 encoded LangSmith API key